Web/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Interfaces;
using Core.Models;
using Web.Interfaces;
using Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Web.Filters;

namespace Web.Controllers
{
    [ValidateModelState]
    public class ProductsController : Controller
    {
        private readonly IProductViewModelsService _productsService;

        public ProductsController(IProductViewModelsService productsService)
        {
            _productsService = productsService;
        }
        public async Task<IActionResult> Index(ProductCategoryViewModel productCategory)
        {
            var products = productCategory.Category == 0 ?
                await _productsService.GetProductsAsync() :
                await _productsService.GetProductsByCategory(productCategory.Category);
            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await _productsService.GetProductByIdAsync(id);
            return View(product);
        }
    }
}

Web/Views/Shared/Components/Categories/Default.cshtml
@model ProductCategoryViewModel

<form asp-controller="Products" asp-action="Index" method="get">
    <div class="form-group">
        <select class="form-control" asp-for="@Model.Category" asp-items="@Model.Categories">
            <option value="0">Select Category</option>
        </select>
        </div>
        <button type="submit" class="btn btn-secondary">Filter</button>
</form>