Web/ViewModels/OrderViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace Web.ViewModels
{
    public class OrderViewModel
    {
        public CustomerViewModel Customer { get; set; }
        public IEnumerable<OrderItemViewModel> Items { get; set; } = new List<OrderItemViewModel>();
        public decimal Total => Items.Sum(x => x.Total);
    }
}

Web/Controllers/OrderController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.ViewModels;
using AutoMapper;
using Web.Interfaces;
using Web.Filters;

namespace Web.Controllers
{
    [ValidateModelState]
    public class OrderController : Controller
    {
        private readonly IOrderViewModelService _orderService;
        private readonly ICartViewModelService _cartService;
        private readonly IMapper _mapper;

        public OrderController(IOrderViewModelService orderService, ICartViewModelService cartService, IMapper mapper)
        {
            _orderService = orderService;
            _cartService = cartService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Submit(OrderViewModel order)
        {
            await _orderService.CheckoutAsync(order);
            
            return View(order);
        }
    }
}

Web/Views/Order/Index.cshtml
@model OrderViewModel
<form asp-controller="Order" asp-action="Submit" method="post">
    <div class="form-group">
        <input class="form-control" placeholder="First name" asp-for="@Model.Customer.FirstName">
        <span asp-validation-for="@Model.Customer.FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="Last name" asp-for="@Model.Customer.LastName">
        <span asp-validation-for="@Model.Customer.LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="E-Mail" asp-for="@Model.Customer.Email">
        <span asp-validation-for="@Model.Customer.Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="Phone" asp-for="@Model.Customer.Phone">
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="Street" asp-for="@Model.Customer.Address.Street">
        <span asp-validation-for="@Model.Customer.Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="City" asp-for="@Model.Customer.Address.City">
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="Postal Code" asp-for="@Model.Customer.Address.PostalCode">
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="Country" asp-for="@Model.Customer.Address.Country">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    }

Web/Views/Order/Submit.cshtml
@model OrderViewModel

<h5>Thank you for submitting your order.</h5>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Product name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>@item.ProductName</td>
                <td>$@item.UnitPrice</td>
                <td>@item.Quantity</td>
            </tr>
        }
        <tr>
            <td></td>
            <td style="font-weight:bold">Total</td>
            <td style="font-weight:bold">$@Model.Total</td>
        </tr>
    </tbody>
</table>