Web/ViewComponents/CartViewComponent.cs
using Web.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewComponents
{
    public class CartViewComponent : ViewComponent
    {
        const string SessionProductIdsKey = "SessionProductIdsKey";
        private readonly ICartViewModelService _cartService;

        public CartViewComponent(ICartViewModelService cartService)
        {
            _cartService = cartService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            /*
            var str = HttpContext.Session.GetString(SessionProductIdsKey);
            var cartCount = 0;
            if (!string.IsNullOrEmpty(str))
            {
                var ids = JsonConvert.DeserializeObject<Dictionary<int,int>>(str);
                cartCount = ids.Count;
            }
            return View(cartCount);
            */
            return View(await _cartService.CountAsync());
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">

        <partial name="_NavBar" />
        @RenderBody()
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Web/Views/Shared/_NavBar.cshtml
<div class="container-fluid">
    <div class="row justify-content-between">
        <div class="col-auto mr-auto">
            <a class="navbar-brand" href="/">Store</a>
        </div>
        <div class="col-auto">
            <vc:cart></vc:cart>
        </div>
    </div>
</div>